#pragma once

#define MYKEY_LEFT 0x01
#define MYKEY_RIGHT 0x02
#define MYKEY_UP 0x04
#define MYKEY_DOWN 0x08
#define MYKEY_LSHIFT 0x10
#define MYKEY_SHOT 0x20
#define MYKEY_BOMB 0x40
#define MYKEY_DASH 0x80

enum GAMEMODE{GM_TOP, GM_PLAY, GM_OPTION, GM_EXIT, GM_PRACTICE, GM_REPLAY};
enum SELECTMODE{SE_ARCADE, SE_PRACTICE, SE_REPLAY, SE_OPTION, SE_EXIT};